### ISSUE TITLE
Error while executing tests

### ISSUE THREAD

**Issue by nortc** [agoncal/agoncal-application-petstore-ee7#9]
Hello,

I have this error with wildfly 8.2.1, 9.0.2, 10.1.0. When executing mvn clean test -Parquillian-wildfly-remote I get a ClassNotFound:

2016-10-04 05:57:12,423 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 56) MSC000001: Failed to start service jboss.persistenceunit."ca3058bc-02e9-4ad3-a350-36d66f27ac52.war#applicationPetstorePU": org.jboss.msc.service.StartException in service jboss.persistenceunit."ca3058bc-02e9-4ad3-a350-36d66f27ac52.war#applicationPetstorePU": java.lang.NoClassDefFoundError: org/agoncal/application/petstore/model/UserRole
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:172) [wildfly-jpa-8.2.1.Final.jar:8.2.1.Final]
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:117) [wildfly-jpa-8.2.1.Final.jar:8.2.1.Final]
	at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.8.0_101]
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:474)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:182) [wildfly-jpa-8.2.1.Final.jar:8.2.1.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_101]
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: java.lang.NoClassDefFoundError: org/agoncal/application/petstore/model/UserRole

In Maven I get this error stack...

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.agoncal.application.petstore.model.AddressTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.656 sec - in org.agoncal.application.petstore.model.AddressTest
Running org.agoncal.application.petstore.model.CategoryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.agoncal.application.petstore.model.CategoryTest
Running org.agoncal.application.petstore.model.CountryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.agoncal.application.petstore.model.CountryTest
Running org.agoncal.application.petstore.model.CreditCardTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.agoncal.application.petstore.model.CreditCardTest
Running org.agoncal.application.petstore.model.CustomerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.13 sec - in org.agoncal.application.petstore.model.CustomerTest
Running org.agoncal.application.petstore.model.ItemTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.124 sec - in org.agoncal.application.petstore.model.ItemTest
Running org.agoncal.application.petstore.model.OrderLineTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.agoncal.application.petstore.model.OrderLineTest
Running org.agoncal.application.petstore.model.ProductTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.agoncal.application.petstore.model.ProductTest
Running org.agoncal.application.petstore.model.PurchaseOrderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.044 sec - in org.agoncal.application.petstore.model.PurchaseOrderTest
Running org.agoncal.application.petstore.rest.CategoryEndpointTest
Okt 04, 2016 5:35:22 AM org.xnio.Xnio <clinit>
INFO: XNIO version 3.2.0.Beta4
Okt 04, 2016 5:35:23 AM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.2.0.Beta4
Okt 04, 2016 5:35:23 AM org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version (unknown)
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.163 sec - in org.agoncal.application.petstore.rest.CategoryEndpointTest
Running org.agoncal.application.petstore.rest.CountryEndpointTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.453 sec - in org.agoncal.application.petstore.rest.CountryEndpointTest
Running org.agoncal.application.petstore.rest.CustomerEndpointTest
Okt 04, 2016 5:35:30 AM org.jboss.as.arquillian.container.ArchiveDeployer undeploy
WARN: Cannot undeploy: 11948ccf-577d-4b20-bd04-457913eb1ce5.war
org.jboss.as.controller.client.helpers.standalone.ServerDeploymentHelper$ServerDeploymentException: java.lang.Exception: "WFLYCTL0216: Management resource '[(\"deployment\" => \"11948ccf-577d-4b20-bd04-457913eb1ce5.war\")]' not found"
        at org.jboss.as.controller.client.helpers.standalone.ServerDeploymentHelper.undeploy(ServerDeploymentHelper.java:114)
        at org.jboss.as.arquillian.container.ArchiveDeployer.undeploy(ArchiveDeployer.java:55)
        at org.jboss.as.arquillian.container.CommonDeployableContainer.undeploy(CommonDeployableContainer.java:152)

Anz idea what I did wrong?

**Comment by agoncal** [comment]
Fixed with https://github.com/agoncal/agoncal-application-petstore-ee7/commit/fc87293bfd603828a44810081d7c3dc51ca70262
